-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,(100*sum(discount_applied='Yes')/count(*)) as percentage
from cust_table
group by item_purchased
order by percentage DESC
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
CASE when previous_purchases=1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from cust_table)
select customer_segment,count(*)
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?


with item_ranking as(
select category,item_purchased,count(customer_id) as item_count,dense_rank() over (partition by category 
order by count(customer_id) DESC) as item_rank from cust_table
group by category,item_purchased



) 
select item_rank,category,item_purchased,item_count from item_ranking
where item_rank<=3;
	
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id),subscription_status
from cust_table
where previous_purchases>5 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as revenue
from cust_table
group by age_group
order by revenue DESC;

